version: '3.9'

services:
  react-native:
    build: .docker/react/Dockerfile
    image: southem/expo-cli
    container_name: react-native
    volumes:
      - ./:/home/node/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- /dev/bus/usb:/dev/bus/usb # Linux
      #- /home/$USER/.android:/home/node/.android # Linux
      - /Users/$USER/.android:/home/node/.android # Mac OS
      - type: bind
        source: /usr/bin/open
        target: /tmp/open
    working_dir: /workspace
    ports:
      - 8081:8081
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006 # browser
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: "$(hostname -i | cut -d' ' -f1)"
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      #ADB_IP: 192.168.1.90

# docker build -t southem/expo-cli .
# https://github.com/uber/baseweb
# https://github.com/navneetkarnani/vscode-expo-starter
# https://dev.to/mandraketech/developing-on-expo-with-ios-using-vscode-and-docker-5hf
