version: '3.7'

services:
  react-native:
    build: .
    image: southem/expo-cli
    container_name: react-native
    volumes:
      #- code:/workspace
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- /dev/bus/usb:/dev/bus/usb # Linux
      #- /home/$USER/.android:/home/node/.android # Linux
      - /Users/$USER/.android:/home/node/.android # Mac OS
      #- type: bind
      #  source: /usr/bin/open
      #  target: /tmp/open
      # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vs-server:/home/node/.vscode-server
    working_dir: /workspace
    ports:
      - 8081:8081
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006 # browser
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: 192.168.1.90
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      #ADB_IP: 192.168.1.90

volumes:
  vs-server: {}
  code:
    driver: local
    driver_opts:
      type: none
      #o: addr=storage,nolock,soft,rw,async,nfsvers=4
      o: bind
      device: ":/mnt"

# docker build -t southem/expo-cli .
# https://github.com/uber/baseweb
# https://github.com/navneetkarnani/vscode-expo-starter
# https://dev.to/mandraketech/developing-on-expo-with-ios-using-vscode-and-docker-5hf
