version: '3.9'

services:
  react-native:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: southem/vscode-expo-starter
    #image: io.ghcr.navneetkarnani.vscode-expo-starter
    container_name: react-native
    volumes:
      - ..:/home/node/workspace:cached
      - vs-server:/home/node/.vscode-server
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/node/workspace
    ports:
      - 8081:8081
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006 # browser
    tty: true

volumes:
  vs-server: {}
  code: {}
